### ISSUE TITLE
Hard-coded relative path in test/tuner.cc

### ISSUE THREAD

**Issue by OursDesCavernes** [CNugteren/CLTune#40]
Hello,

I'm writing a Gentoo package for CLTune: [sci-libs/cltune](https://github.com/OursDesCavernes/cavernlay/tree/master/sci-libs/cltune)

The Gentoo package manager (Portage) can perform unit tests automatically after build and before installation.
A hard-coded relative path at [test/tuner.cc#L46](https://github.com/CNugteren/CLTune/blob/cba89a40d8320b0da4c4ea888fc5130b301e3201/test/tuner.cc#L46) breaks the tests as it assumes that the binary is run from a subdirectory of the source root.

An option would be to pass the source or sample base path by argument and fall back to ../samples/ if omitted.

What do you think ?

**Comment by CNugteren** [comment]
You are right, that is an issue. Luckily the tuner also accepts kernels as strings instead of loading them from file: I changed this in the latest version of the `development` branch. It changes test coverage slightly, but passing arguments to the Catch framework is apparently also not so trivial. I believe this is the best solution for now.
